global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: discovery-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["discovery-server:8761"]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: customer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["customer-service:8082"]

  - job_name: loan-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["loan-service:8083"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8084"]

  - job_name: loan-product-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["loan-product-service:8085"]

  - job_name: accounting-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["accounting-service:8086"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8087"]

  - job_name: branch-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["branch-service:8088"]
